### ISSUE TITLE
Change directory of file download 

### ISSUE THREAD

**Issue by theleanbow** [riolubruh/SplitLargeFiles#6] opened 2023-04-07 17:03 UTC
The readme says 
[Downloading the file results in the reassembled original file being put in the directory of your choice.](https://github.com/riolubruh/SplitLargeFiles#main-features)
but I can't find the option to change the directory anwhere.

**Comment by riolubruh** [comment] 2023-04-07 19:53
You're absolutely correct: the README is outdated. The plugin used to allow you to choose where to save the files in a "Save as..." window, however due to technical problems, this functionality had to be removed, and instead I changed it to open the directory of the file after a download completes.

**Comment by riolubruh** [comment] 2023-04-07 20:45
The README has been updated

**Comment by l-Nuril-l** [comment] 2023-05-11 11:00
Is the plugin broken? Parts do not join.

**Comment by l-Nuril-l** [comment] 2023-05-11 11:00
@riolubruh Is the plugin broken? Parts do not join.

**Comment by riolubruh** [comment] 2023-05-12 21:53
> @riolubruh Is the plugin broken? Parts do not join.

The graphical part of the plugin is currently not working correctly. Files still should be able to be uploaded and split normally, though you will need to use the "Copy Download Links" button in the right-click menu until the problem is fixed.

**Comment by riolubruh** [comment] 2023-05-13 01:16
@l-Nuril-l I have implemented the half-fix committed to the original repository. It should be possible to download the split files by clicking "Download Large File" in the right-click / context menu.

**Closed as completed** 2023-10-18 00:30 UTC
Labels: enhancement
